name: ARC Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set

    steps:
      - name: Show runner
        run: |
          echo "Running inside Kubernetes!"
          echo "Hostname:"
          hostname

      - name: Show OS
        run: |
          uname -a

      - name: Show environment
        run: |
          whoami
          pwd
